#!/bin/bash
# Usage: ./batch_demldr /sharedata/yxtang/XDA19090126Share

DATAPATH=$1

# Subsidence
folder=("center-west" "NorthEast" "Tanwan" "west")

echo --------------------Subsidence Start-----------------------
for i in ${folder[@]};
do
    echo $i:
    for j in $DATAPATH/Subsidence/$i/*;
    do
        if [ -d $j ];
        then
            for k in $j/*;
            do
                if [ -d $k ];
                then
                    if [ ! -f $k/DEM/exDEM.ldr ];
                    then
                        echo $k: exDEM.ldr-----------No
                        ./rewrite $k
                    else
                        echo $k: exDEM.ldr-----------Yes
                    fi
                    
                    if [ ! -f $k/DEM/exDEM.rmghe ];
                    then
                        echo $k: exDEM.rmghe---------No
                        cp $k/DEM/TanDEM.dem $k/DEM/exDEM.rmghe
                    else
                        echo $k: exDEM.rmghe---------Yes
                    fi
                fi
            done
        fi
    done
done

echo "HuaBei"
for j in $DATAPATH/Subsidence/HuaBei/Sentinel-1/*;
do
    if [ -d $j ];
    then
        for k in $j/*;
        do
            if [ -d $k ];
            then
                if [ ! -f $k/DEM/exDEM.ldr ];
                then
                    echo $k: exDEM.ldr-----------No
                    ./rewrite $k
                else
                    echo $k: exDEM.ldr-----------Yes
                fi
                
                if [ ! -f $k/DEM/exDEM.rmghe ];
                then
                    echo $k: exDEM.rmghe---------No
                    cp $k/DEM/TanDEM.dem $k/DEM/exDEM.rmghe
                else
                    echo $k: exDEM.rmghe---------Yes
                fi
            fi
        done
    fi
done

echo --------------------Subsidence End------------------------

echo ""

# Subsidence2
folder2=("NorthEast" "West")
folder3=("1225Added" "new-added")

echo --------------------Subsidence-2 Start--------------------

for i in ${folder2[@]};
do
    echo $i
    for j in $DATAPATH/Subsidence-2/$i/*;
    do
        if [ -d $j ];
        then
            for k in $j/*;
            do
                if [ -d $k ];
                then
                    if [ ! -f $k/DEM/exDEM.ldr ];
                    then
                        echo $k: exDEM.ldr-----------No
                        ./rewrite $k
                    else
                        echo $k: exDEM.ldr-----------Yes
                    fi
                    
                    if [ ! -f $k/DEM/exDEM.rmghe ];
                    then
                        echo $k: exDEM.rmghe---------No
                        cp $k/DEM/TanDEM.dem $k/DEM/exDEM.rmghe
                    else
                        echo $k: exDEM.rmghe---------Yes
                    fi
                fi
            done
        fi
    done
done

for i in ${folder3[@]};
do
    echo $i
    for k in $DATAPATH/Subsidence-2/$i/*;
    do
        if [ -d $k ];
        then
            if [ ! -f $k/DEM/exDEM.ldr ];
            then
                echo $k: exDEM.ldr-----------No
                ./rewrite $k
            else
                echo $k: exDEM.ldr-----------Yes
            fi
            
            if [ ! -f $k/DEM/exDEM.rmghe ];
            then
                echo $k: exDEM.rmghe---------No
                cp $k/DEM/TanDEM.dem $k/DEM/exDEM.rmghe
            else
                echo $k: exDEM.rmghe---------Yes
            fi
        fi
    done
done


echo --------------------Subsidence-2 End---------------------

