#!/bin/bash


# 1. acquire task

task=""
i=0;

echo
echo "Task List:"
echo "-----------------------------------------------------------------"
while read line
do
    if [ ! -d $line ];
    then
        echo "Floder($line) does not exist!!! "
    else
        echo $line
        task[$i]=$line
        let i+=1
    fi
done < task.txt
echo "-----------------------------------------------------------------"
echo 

# 2. acquire parameter

totalNum=${#task[@]}

#for((j=0;j<$totalNum;j++));
#do
#    tt=${task[$j]}
#    echo $tt
#    logName=${tt##*/}
#    echo "Log file Name: $logName"
#done

echo "Task tatal number: $totalNum"
echo

# 3. job scheduler

maxNodeNum=10 # max number of running tasks

# 3.1

jobid=""
jobNum=0

if [ $totalNum -le $maxNodeNum ];
then
    for((k=0;k<$totalNum;k++));
    do
        DATA_PATH=${task[$k]}
        logName=${DATA_PATH##*/}
        jobInfo=`sbatch job1.sbatch $DATA_PATH log/${logName}`
        jobid[$jobNum]=${jobInfo##* }
        echo "  Submit: $DATA_PATH"
        let jobNum+=1
        
        wait
    done

    echo "Total tasks: $totalNum    Submited Tasks: $jobNum"
    echo
    echo "Submit Jobs completed!"
    echo

    exit
echo
    
fi

for((k=0;k<$maxNodeNum;k++));
do
    DATA_PATH=${task[$k]}
    logName=${DATA_PATH##*/}
    jobInfo=`sbatch job1.sbatch $DATA_PATH log/${logName}`
    jobid[$jobNum]=${jobInfo##* }
    echo "  Submit: $DATA_PATH"
    #echo "${jobid[$jobNum]}"
    let jobNum+=1
    
    wait
done
echo

# 3.2

while [ $jobNum -lt $totalNum ]
do
    sleep 10m
    endNum=`cat jobid/*.job|grep "Task End"|wc -l`
    if [ $endNum -gt "0" ];
    then
        temp=$jobNum
        runningNum=`expr $temp - $endNum`
        submitedNum=$jobNum # number of submited jobs
        unsubmitNum=`expr $totalNum - $endNum` # number of unsubmit jobs
        nextSubmitNum=`expr $maxNodeNum - $runningNum`

        if [ `expr $unsubmitNum + $runningNum` -lt $maxNodeNum ];
        then
            nextSubmitNum=$unsubmitNum
        fi
        
        echo 
        echo "  Total tasks: $totalNum    Submited Tasks: $submitedNum   Running Tasks: $runningNum    Finished Tasks: $endNum   Next Submit Tasks: $nextSubmitNum"
        echo

        for((i=0;i<$nextSubmitNum;i++));
        do
            DATA_PATH=${task[$jobNum]}
            logName=${DATA_PATH##*/}
            jobInfo=`sbatch job1.sbatch $DATA_PATH log/${logName}`
            jobid[$jobNum]=${jobInfo##* }
            echo "  Submit: $DATA_PATH"
            let jobNum+=1
            
            wait
        done
    else
        echo "wait..."
        echo
    fi
    
done

# 4 Information

endNum=`cat jobid/*.job|grep "Task End"|wc -l`

echo
echo "Total tasks: $totalNum    Submited Tasks: $jobNum   Running Tasks: `expr $jobNum - $endNum`    Finished Tasks: $endNum"
echo
echo "Submit Jobs completed!"


