#!/bin/bash

logDP=$1
filename=$2

if [ ! -d $logDP ];
then
    echo "Please input right log-folder!"
    exit 0
fi

if [ -f $filename ];
then
    echo "Delete file with same name!"
    rm $filename
fi

echo Orbit, Phase1, InSARPair, S1TopoPhase, Phase2, ComplexPro, S1SimDEM, MeanCoh, Musk, PSC, triEdgeEst, Integration, Total, Numsar, Masterid, Point > $filename


for i in `ls $logDP`;
do
    if [ ! -d $logDP/$i ];
    then
        fp=$logDP/$i

        orbit=${i%%_*}
        
        tmp=`cat $fp|grep "(Phase1: Compute and Merge) The time:"`
        tmp1=${tmp##*: }
        phase1=${tmp1%%s*}
        if [ -z "$phase1" ];
        then
            phase1="xxx"
        fi

        tmp=`cat $fp|grep "(InSARPairGen) The time is:"`
        tmp1=${tmp##*: }
        insarpairgen=${tmp1%%s*}
        if [ -z "$insarpairgen" ];
        then
            insarpairgen="xxx"
        fi

        tmp=`cat $fp|grep "(S1TopoPhase) The time:"`
        tmp1=${tmp##*: }
        s1topophase=${tmp1%%s*}
        if [ -z $s1topophase ];
        then
            s1topophase="xxx"
        fi

        tmp=`cat $fp|grep "(S1Coh/S1BaseLine) The time:"`
        tmp1=${tmp##*: }
        phase2=${tmp1%%s*}
        if [ -z "$phase2" ];
        then
            phase2="xxx"
        fi
        
        tmp1=`cat $fp|grep "(ComplexPro) The time is: "|head -n 1`
        complexpro1=${tmp1##*: }
        tmp2=`cat $fp|grep "(ComplexPro) The time is: "|tail -n 1`
        complexpro2=${tmp2##*: }
        if [ -z "$complexpro1" ] || [ -z "$complexpro2" ];
        then
            complexpro="xxx"
        else
            complexpro=`expr ${complexpro1%%s*} + ${complexpro2%%s*}`
        fi

        tmp=`cat $fp|grep "(S1SimDem) The time is:"`
        tmp1=${tmp##*: }
        s1simdem=${tmp1%%s*}
        if [ -z "$s1simdem" ];
        then
            s1simdem="xxx"
        fi
        
        tmp=`cat $fp|grep "(MeanCoh) The running time is:"`
        tmp1=${tmp##*: }
        meancoh=${tmp1%%s*}
        if [ -z "$meancoh" ];
        then
            meancoh="xxx"
        fi

        tmp=`cat $fp|grep "(Musk) The running time is:"`
        tmp1=${tmp##*: }
        musk=${tmp1%%s*}
        if [ -z "$musk" ];
        then
            musk="xxx"
        fi

        tmp=`cat $fp|grep "(PSC) The running time is:"`
        tmp1=${tmp##*: }
        psc=${tmp1%%s*}
        if [ -z "$psc" ];
        then
            psc="xxx"
        fi
        
        tmp=`cat $fp|grep "(triEdgeEst) The running time is:"`
        tmp1=${tmp##*: }
        triedgeest=${tmp1%%s*}
        if [ -z "$triedgeest" ];
        then
            triedgeest="xxx"
        fi

        tmp=`cat $fp|grep "NUMSAR = "`
        numsar=${tmp##* }
        if [ -z "$numsar" ];
        then
            numsar="xxx"
        fi
        
        tmp=`cat $fp|grep "MASTER_ID = "`
        masterid=${tmp##* }
        if [ -z "$masterid" ];
        then
            masterid="xxx"
        fi
        
        echo \ $orbit, $phase1, $insarpairgen, $s1topophase, $phase2, $complexpro, $s1simdem, $meancoh, $musk, $psc, $triedgeest, , , $numsar, $masterid >> $filename
    fi
done



