#!/bin/bash

path=$1
step=$2

path1=$path/data/
path2=$path/sample/

date=("20180912/" "20180924/" "20181006/" "20181018/")
iw=("IW1/" "IW2/" "IW3/")
burst=("burst-1.rmg" "burst-2.rmg" "burst-3.rmg" "burst-4.rmg" "burst-5.rmg" "burst-6.rmg" "burst-7.rmg" "burst-8.rmg" "burst-9.rmg")
derampPhase=("derampPhase-1.rmg" "derampPhase-2.rmg" "derampPhase-3.rmg" "derampPhase-4.rmg" "derampPhase-5.rmg" "derampPhase-6.rmg" "derampPhase-7.rmg" "derampPhase-8.rmg" "derampPhase-9.rmg") 

bDe=("bDe-1.rmg" "bDe-2.rmg" "bDe-3.rmg" "bDe-4.rmg" "bDe-5.rmg" "bDe-6.rmg" "bDe-7.rmg" "bDe-8.rmg" "bDe-9.rmg")

bDerampFine=("bDerampFine-1.rmg" "bDerampFine-2.rmg" "bDerampFine-3.rmg" "bDerampFine-4.rmg" "bDerampFine-5.rmg" "bDerampFine-6.rmg" "bDerampFine-7.rmg" "bDerampFine-8.rmg" "bDerampFine-9.rmg")

dePhaseFine=("dePhaseFine-1.rmg" "dePhaseFine-2.rmg" "dePhaseFine-3.rmg" "dePhaseFine-4.rmg" "dePhaseFine-5.rmg" "dePhaseFine-6.rmg" "dePhaseFine-7.rmg" "dePhaseFine-8.rmg" "dePhaseFine-9.rmg")

bDerampFineRe=("bDerampFineRe-1.rmg" "bDerampFineRe-2.rmg" "bDerampFineRe-3.rmg" "bDerampFineRe-4.rmg" "bDerampFineRe-5.rmg" "bDerampFineRe-6.rmg" "bDerampFineRe-7.rmg" "bDerampFineRe-8.rmg" "bDerampFineRe-9.rmg")

if [ "$step" == "2" ];
then
    for i in ${date[@]}; 
    do
        for j in ${iw[@]}; 
        do
            for k in ${burst[@]}; 
            do
                echo $path1$i$j$file$k   $path2$i$j$file$k
                cmd=`diff $path1$i$j$file$k $path2$i$j$file$k`
                echo $cmd
            done
        done
    done
fi


if [ "$step" == "3" ]; 
then
    str="dcPara.rmg"
    for i in ${date[@]}; 
    do
        for j in ${iw[@]}; 
        do
            echo $path1$i$j$file$str   $path2$i$j$file$str
            cmd=`diff $path1$i$j$str $path2$i$j$file$str`
            echo $cmd
            
        done
    done
fi

if [ "$step" == "4" ]; 
then
    for i in ${date[@]:1:3};
    do
        for j in ${iw[@]}; 
        do
            for k in ${derampPhase[@]}; 
            do
                echo $path1$i$j$file$k   $path2$i$j$file$k
                cmd=`diff $path1$i$j$file$k $path2$i$j$file$k`
                echo $cmd
            done
        done
    done
fi


if [ "$step" == "5" ]; 
then
    for i in ${date[@]:1:3};
    do
        for j in ${iw[@]}; 
        do
            for k in ${bDe[@]};
            do
                echo $path1$i$j$file$k   $path2$i$j$file$k
                cmd=`diff $path1$i$j$file$k $path2$i$j$file$k`
                echo $cmd
            done
        done
    done
fi

if [ "$step" == "6" ]; 
then
    for i in ${date[@]:1:3};
    do
        for j in ${iw[@]}; 
        do
            for k in ${bDerampFine[@]}; 
            do
                echo $path1$i$j$file$k   $path2$i$j$file$k
                cmd=`diff $path1$i$j$file$k $path2$i$j$file$k`
                echo $cmd
            done
        done
    done
fi

if [ "$step" == "6" ]; 
then
    for i in ${date[@]:1:3};
    do
        for j in ${iw[@]}; 
        do
            for k in ${dePhaseFine[@]}; 
            do
                echo $path1$i$j$file$k   $path2$i$j$file$k
                cmd=`diff $path1$i$j$file$k $path2$i$j$file$k`
                echo $cmd
            done
        done
    done
fi

if [ "$step" == "7" ]; 
then
    for i in ${date[@]:1:3};
    do
        for j in ${iw[@]}; 
        do
            for k in ${bDerampFineRe[@]}; 
            do
                echo $path1$i$j$file$k   $path2$i$j$file$k
                cmd=`diff $path1$i$j$file$k $path2$i$j$file$k`
                echo $cmd
            done
        done
    done
fi

if [ "$step" == "8" ]; 
then
    for i in ${date[@]};
    do
        for j in ${iw[@]}; 
        do
            echo ${path1}${i}${j}${file}IWpj.rmg   ${path2}${i}${j}${file}/IWpj.rmg
            cmd=`diff ${path1}${i}${j}${file}/IWpj.rmg ${path2}${i}${j}${file}/IWpj.rmg`
            echo $cmd
        done
    done
fi
